from sqlalchemy import Column, String, ForeignKey, Integer, Text
from sqlalchemy.orm import relationship
from src.config.database import Base
from .mixins import UUIDMixin, TimestampMixin


class GeneratedSpreadsheet(Base, UUIDMixin, TimestampMixin):
    """Tracks metadata for every Excel file generated by the spreadsheet tool."""
    __tablename__ = "generated_spreadsheets"

    conversation_id = Column(
        String,
        ForeignKey("conversations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    org_id = Column(
        String,
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    title = Column(String(500), nullable=False)

    # Populated once the .xlsx file has been written to disk
    file_path = Column(String(1000), nullable=True)   # e.g. storage/spreadsheets/<uuid>.xlsx
    file_url  = Column(String(1000), nullable=True)   # e.g. http://host/storage/spreadsheets/<uuid>.xlsx
    sheet_count = Column(Integer, default=1)
